-- Drop and recreate Widgets table (Example)

DROP TABLE IF EXISTS to_dos CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
CREATE TABLE categories (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);
CREATE TABLE to_dos (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  category INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  text VARCHAR(255) NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT FALSE
);


